version: '3.8'

services:
  web:
    build: .
    command: gunicorn done_dusted.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - data_volume:/app/data
    env_file:
      - .env
    depends_on:
      - db-init

  nginx:
    image: nginx:1.21-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  db-init:
    image: alpine:latest
    command: sh -c "mkdir -p /app/data && chmod 777 /app/data"
    volumes:
      - data_volume:/app/data

volumes:
  static_volume:
  media_volume:
  data_volume:
